### ISSUE TITLE
GGEE installation failed

### ISSUE THREAD

**Issue by CharlesChanBiostat** [vstanislas/GGEE#1]
Dear Sir or Madam
       The R package "GGEE" is very helpful for our study, and we are all interseted in it. But some error happened when I installed the package. 

"D:/PROGRA~1/RSOFTW~1/R-34~1.4/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/dell/AppData/Local/Temp/Rtmp0aknpm/devtools156450205aa4/vstanislas-GGEE-31dc4d8"  \
  --library="D:/Program Files (x86)/R software/R-3.4.4/library"  \
  --install-tests 

ERROR: dependency 'ridgeAdap' is not available for package 'GGEE'
* removing 'D:/Program Files (x86)/R software/R-3.4.4/library/GGEE'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by vstanislas** [comment]
Dear Sir,

Thank you for your interest in our package.
In order to install GGEE you will need to first install the package ridgeAdap using the following command:
devtools::install_github("jbecu/ridgeAdap")
The installation of GGEE should work properly after this,

Best regards,

Virginie

**Comment by vstanislas** [comment]
Dear Sir,

Thank you for your interest in our package and my apologies for the  
late answer.
In order to install GGEE you will need to first install the package  
ridgeAdap using the following command:
devtools::install_github("jbecu/ridgeAdap")
The installation of GGEE should work properly after this,

Best regards,

Virginie

CharlesChanBiostat <notifications@github.com> a écrit :

**Comment by JrOcira** [comment]
Dear dr. Virginie,
I have been recently trying to install the package but have been having error 

Error: package or namespace load failed for ‘GGEE’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/junior/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-GGEE/00new/GGEE/libs/GGEE.so':
  /home/junior/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-GGEE/00new/GGEE/libs/GGEE.so: undefined symbol: dgesdd_
Error: loading failed
Execution halted

I was wondering what the problem could be with the compiler or because I had RCPP installed before or something else. I tried following the recommendation of creating a .R/Makevars file in the home directory but still I receive the error. If this is the case, is it possible to include the file as an example

Kind Regards,
Junior Ocira
Thanks for your

**Comment by vstanislas** [comment]
Dear Junior Ocira,

Thanks a lot for your interest and for reporting this issue.

After investigation, the problem is coming from missing lib specifications of the libraries blas and lapack on linux and windows during the installation (the problem does not occur with mac as it apparently does not need those path definitions).

There are now two new Makevars files in the R/src/ folder that should correct for this problem (following https://www.rdocumentation.org/packages/RcppArmadillo/versions/0.9.600.4.0/topics/RcppArmadillo-package).

Please let me know if this solution works out for you,

Best wishes,

Virginie

**Comment by JrOcira** [comment]
Dear Dr. Virginie,
Thanks for the solution, it works now. I am able to install the package with no error in Linux. For windows, there are still a problem with the ridgeAdap pacakge as it fails to install though installation is possible with no error on Linux. 
I am opening another issue for an error I found when I follow the Vignette.

Kind Regards,
Junior Ocira
