### ISSUE TITLE
Error running BuiltEpiVar function

### ISSUE THREAD

**Issue by JrOcira** [vstanislas/GGEE#2]
Dear Dr. Virginie,
Greetings! I have been following the Vignette and been able to simulate the phenotype and genotype. However when I run the BuiltEpiVar function, I get this error.

Int <- BuiltEpiVar(Geno$X, Pheno$y, method="GGEE", listGenesSNP=Geno$listGenesSNP)

                     Error in GGEE(X = X, Y, listGenesSNP = listGenesSNP, idSubs) : 
                     argument "idSubs" is missing, with no default

I didn't see an explaination of the idSubs in the Vignette and when I checked the BuiltEpiVar function in GLmodel.r, I saw that this idSubs is a dataframe with variables idSubs$idTrain and idSubs$idTest. 

I thought of creating a dataframe with ids for the train and test dataset (300 for test and 300 for train) as below;
######################################################
idTrain <- seq(1,300,1)
idTest <- seq(301,600,1)
idSubs <- data.frame(idTrain, idTest)
colnames(idSubs) <- c("idTrain", "idTest")

Int <- BuiltEpiVar(Geno$X, Pheno$y, method="GGEE", listGenesSNP=Geno$listGenesSNP, idSubs = idSubs)

**However after running this, I get 28 warnings all showing**

              In A/sqrt(A %*% A) :
              Recycling array of length 1 in vector-array arithmetic is deprecated.
              Use c() or as.vector() instead.
########################################################
Could you help throw more light on this?

Thanks for your response.
Kind Regards

**Comment by vstanislas** [comment]
Dear JrOcira,

First all my apologies for the late answer. 
You were correct, the vignette was not updated to the last changes of the package which is now done.
idSubs is a list providing the indices of the samples used for training ($idTrain) or testing ($idTest).  
(The training group is used to construct the interaction variables and to estimate the Group LASSO coefficients. The test group is used for the cleaning step to compute the permuted p-values.)

it can be generated this way:

```r
n <- dim(Geno$X)[1]
portionTrain <- 1/2
idTrain <- sample(1:n, size=n*portionTrain)
idTest <- (1:n)[-idTrain]
idSubs <- list(idTrain=idTrain[order(idTrain)], idTest=idTest)
```


Regarding the warnings occurring with BuiltEpiVar(), they do not impact the calculation and simply occur because of the format of the object sqrt(A %*% A). The code has now been updated and the warnings should not appear anymore.

All the best
